"""
Query API endpoints.
Handles RAG queries and response generation.
"""

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse

from app.models.schemas import QueryRequest, QueryResponse
from app.services.rag_pipeline import RAGPipeline
from app.utils.logging import get_logger

logger = get_logger(__name__)

router = APIRouter(prefix="/query", tags=["Query"])


@router.post(
    "",
    response_model=QueryResponse,
    summary="Query the RAG system",
    description="Ask a question and get an answer grounded in retrieved documents.",
)
async def query(request: QueryRequest) -> QueryResponse:
    """
    Query the RAG system with a question.
    
    The system will:
    1. Retrieve relevant documents from the vector store
    2. Use the documents as context for the LLM
    3. Generate an answer grounded in the retrieved sources
    4. Return the answer with source citations
    """
    logger.info(
        "query_request_received",
        question=request.question[:100],
        top_k=request.top_k,
        include_sources=request.include_sources,
    )
    
    try:
        pipeline = RAGPipeline()
        response = await pipeline.query(
            question=request.question,
            top_k=request.top_k,
            include_sources=request.include_sources,
        )
        
        logger.info(
            "query_response_generated",
            answer_length=len(response.answer),
            num_sources=len(response.sources),
            query_time_ms=response.query_time_ms,
        )
        
        return response
        
    except Exception as e:
        import traceback
        error_details = traceback.format_exc()
        logger.error(
            "query_error",
            error=str(e),
            error_type=type(e).__name__,
            traceback=error_details,
        )
        raise HTTPException(
            status_code=500,
            detail=f"Query failed: {str(e)}. Error type: {type(e).__name__}",
        )


@router.post(
    "/stream",
    summary="Stream query response",
    description="Ask a question and stream the answer as it's generated.",
)
async def stream_query(request: QueryRequest) -> StreamingResponse:
    """
    Stream a RAG query response.
    
    Returns a streaming response where the answer is sent in chunks
    as it's generated by the LLM. This provides faster time-to-first-token.
    """
    logger.info(
        "stream_query_request_received",
        question=request.question[:100],
        top_k=request.top_k,
    )
    
    try:
        pipeline = RAGPipeline()
        
        async def generate():
            async for chunk in pipeline.stream_query(
                question=request.question,
                top_k=request.top_k,
            ):
                yield chunk
                
        return StreamingResponse(
            generate(),
            media_type="text/plain",
        )
        
    except Exception as e:
        logger.error("stream_query_error", error=str(e))
        raise HTTPException(
            status_code=500,
            detail=f"Streaming query failed: {str(e)}",
        )


@router.get(
    "/sources",
    summary="Get source documents",
    description="Get relevant source documents for a question without generating an answer.",
)
async def get_sources(
    question: str,
    top_k: int = 5,
) -> list[dict]:
    """
    Retrieve relevant source documents for a question.
    
    This endpoint is useful for:
    - Previewing what sources would be used for a query
    - Implementing custom retrieval UI
    - Debugging retrieval quality
    """
    logger.info(
        "sources_request_received",
        question=question[:100],
        top_k=top_k,
    )
    
    try:
        pipeline = RAGPipeline()
        sources = pipeline.get_retrieved_sources(question, top_k)
        
        return [source.model_dump() for source in sources]
        
    except Exception as e:
        logger.error("sources_error", error=str(e))
        raise HTTPException(
            status_code=500,
            detail=f"Failed to retrieve sources: {str(e)}",
        )
